name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths-ignore:
      - 'pr-preview/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  preview:
    concurrency:
      group: preview-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Configure git for reliability
        run: git config --global http.version HTTP/1.1
      - uses: actions/checkout@v4
      - name: Remove old previews
        run: rm -rf pr-preview
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./
          preview-branch: gh-pages
          wait-for-pages-deployment: true
